//URL
const ERR_NOTLOGIN=1005
const ERR_INVALID_USERNAME_OR_PASSWORD=1004
const ERR_INVALID_PERMISSON=1006
const ERR_INVALID_OLD_PASSWORD=1007
const ERR_INVALID_KAPTCHA=1008
const INVALID_DATA=1000


export default {
  ERR_NOTLOGIN,
  ERR_INVALID_USERNAME_OR_PASSWORD,
  ERR_INVALID_PERMISSON,
  ERR_INVALID_OLD_PASSWORD,
  ERR_INVALID_KAPTCHA,
  INVALID_DATA
}
