//URL
const ERR_NOTLOGIN=1005
const ERR_INVALID_USERNAME_OR_PASSWORD=1004
const ERR_INVALID_PERMISSON=1006
const ERR_INVALID_OLD_PASSWORD=1007
const ERR_INVALID_KAPTCHA=1008


export default {
  ERR_NOTLOGIN,
}
